### ISSUE TITLE
Certain keys aren't being recognized

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#10]
The following keys aren't being recognized as being pressed/released:

Caps Lock
Shift
Control
Fn
Win
Alt
Context Menu
Insert
Delete
Home
Num Lock
Print Screen
Scroll Lock
Pause
Home
Page Up
Page Down
End
Up
Down
Left
Right
F1-F12

**Comment by maxrigout** [comment]
Hello Zero3K,

The way my program functions is similar to a multi monitor setup. I haven't implemented a way to get the native resolution of the server/client so they are, therefore, hard coded : line 41 and 42. At the time I wrote this program, the server screen dimensions were 1920x1080 and the client screen dimensions were 2560x1440.
I designed the server to send input only when the mouse reaches the right border of the screen. Then the program "locks" the mouse to the right and sends input to the connected client. Similarly, when the mouse on the client screen reaches the left border, the server stops sending input and "unlocks" the mouse. This process gives the illusion of a multi-display configuration with multiple computers. Therefore before sending any input, the mouse needs to "be on the other computer".

Given that the conditions for sending inputs were met, all but the Fn key work on my end.

I believe the reason that the Fn key doesn't work is because it is not a windows standard key : it is probably used to access other keys such as on a laptop which has limited space. For instance, on my laptop, to hit the Insert key, I need to hold down Fn + Home. Since my program would already send an Insert key press, it doesn't need to send the Fn + Home key combination.

The reason why it might seem that some keys don't work is related to the GUI where normally I would update the GUI based on the input it gets. I did not, however, code every key to appear in the GUI. This was deliberate out of pure laziness.

Thank you for your input, I appreciate your suggestions.

**Comment by Zero3K** [comment]
I think that it should not care about the monitor size. Instead, it should send the mouse and keyboard inputs until the server function is stopped.

**Comment by maxrigout** [comment]
if you'd like the server to continuously send input to the client, then you want to take a look at lines 540 - 586.

Also, I explained how my program works, it is by no means an absolute, in fact, you can code whatever you like. As far as I'm concerned the program works as advertised. Certainly not perfectly, but it works nonetheless.

You opened an issue about certain keys not working and after trying it out, I found that it does indeed work. In order to not just close the issue without an explanation as to why it might not work on your end, I explained to you why it might not work. If you still have an issue with the keys you listed, feel free to continue posting in this thread.
If you think you can improve the program, by all means, please do. Whether it's copy/paste or by forking it, I don't mind. As far as I'm concerned, I uploaded my code "as-is" with no guarantee for support or further improvements.

**Comment by Zero3K** [comment]
I am not a developer. So I can only make a fork that fixes simple issues (such as the one where I asked you to make a VS2019 project for it and to share a binary that doesn't rely on redist packages).

**Comment by Zero3K** [comment]
Can you please fix the other keys not showing up?
