### ISSUE TITLE
Meaning of Server/Client 

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#13]
What is the meaning of Server and Client? I thought that Server was the one that the user wants to have controlled by the Client (unless the Server controls the Client).

**Comment by maxrigout** [comment]
yes the server controls the client. The server is the machine that sends all the inputs to the other machines. Maybe the terms server/client isn't really appropriate, but since I needed machines to connect to another machine, I decided to name the machine they connect to "server" and the machines that connect to the server "clients"
