### ISSUE TITLE
Fix the Readme

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#14]
Please fix the Readme to include a better description, screenshots, etc.

**Comment by Zero3K** [comment]
Also, the Readme is incorrect since what it states isn't possible unless you were to add support for multiple clients.

**Comment by maxrigout** [comment]
a more detailed description on how to use software and how to code is structured would be nice, but it would be very time consuming. Time I don't necessarily have at the moment. Maybe I'll work on it little by little

**Comment by Zero3K** [comment]
I don't care about having it mention how the code is structured. Just a better description, how to use it and screenshots would do.

**Comment by maxrigout** [comment]
fyi, this project isn't about you. If you post an issue, it's because there is an issue with the program. Not because you think the program should work a certain way. If you want to do these things, feel free to repo and add these things yourself.

If people want to contribute to this project, I'm sure it would help them a lot to know how the code works so they don't have to reverse engineer the code.

This isn't the windows/mac store.

**Comment by Zero3K** [comment]
You can add comments to the code then.
