### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#2]
It would be nice if it could support the connection of Gamepads so people can remotely play games with someone by using it. If you do include it, then also include the ability to choose whether to block the connected user(s) from controlling the keyboard/mouse of their PC.

**Comment by maxrigout** [comment]
I suspect gamepads would be significantly more complicated to implement because you can have multiple gamepads connected to a single computer. This was beyond the scope of this project.

I did not want to block the clients input because that could lead to a lot of annoying bugs (I mean, not being able to use your mouse or keyboard if the app shuts down improperly for instance). So I don't want to implement this. Or at least not right now.

**Comment by Zero3K** [comment]
1. Maybe later on?
2. Okay.

**Comment by Zero3K** [comment]
Here's a program that can share gamepads over the Internet:

https://github.com/cezanne/usbip-win
