### ISSUE TITLE
Issue with IP address being used

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#3]
For some reason, it was using an IP address that none of my network adapters were using (which was 192.168.1.8). Please fix it so it uses the proper IP address.

**Comment by maxrigout** [comment]
Hello,

This IP address is hard coded in my program so that I wouldn't have to type it in every time I launched it. If you would like to change its default value, you need to change it at line 453. Otherwise, after activating client mode, you can change the field next to "Server Address" to connect to the correct server.

Thanks

**Comment by Zero3K** [comment]
I still think it would be nice if it auto-detected the IP address and used it instead of having a hard-coded value (or use a list of adapters and let the user use the proper adapter's IP address).

**Comment by maxrigout** [comment]
The hard coded value only applies to the client side and not the server side. If you would like to make improvements, feel free to use what I've done and adapt it to your needs

**Comment by Zero3K** [comment]
How about making it available as a parameter in an INI file? That or making it be empty and allowing the user to manually set it with a drop-down box in case the user connects to other servers and then saving the parameter in the INI file?
