### ISSUE TITLE
Ability to change the options

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#7]
It would be nice if it had the ability to change the DEFAULT_PORT and MAX_CLIENTS options via its dialog box and save them to a .ini file.

**Comment by maxrigout** [comment]
default_port is the port that is used by default. I could add an extra input box where you would enter the port to which you'd like to connect. As far as the ini file, I could just create a file based on the previous session that would save the ip address and the port so that you can reuse it quickly.

**Comment by Zero3K** [comment]
Why did you close this?

**Comment by maxrigout** [comment]
just fixed it
