### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#9]
I tried both my private IP address and the one that is offered via ZeroTier. Both of them didn't work properly. I got the following logs in the console of both the server and client.

![Remote_Server](https://user-images.githubusercontent.com/6194332/97093955-317c6d00-161e-11eb-8cb0-f543e829dba2.png)
![Remote_Client](https://user-images.githubusercontent.com/6194332/97093960-3c370200-161e-11eb-9301-bb58f6b11017.png)

**Comment by maxrigout** [comment]
Hello, the program isn't designed to work on a virtual machine. I suspect if you wanted to do that, you'd have to go through extra channels (since whatever is coming into the virtual machine from the network has to go through the host).
Also the screenshots you provided shows your IP address. I'm unsure whether it's your router's IP or your local IP. If it's your router's IP, I strongly suggest you hide it.

If you'd like me to remove the pictures / post I can do that, just let me know.

**Comment by Zero3K** [comment]
1. I am not using it on a Virtual Machine. I am using it on a Macbook as a Server and my PC as a Client.
2. Its an IP address used by ZeroTier (which is useless to other people unless they join the network I made that uses that IP address range).

**Comment by maxrigout** [comment]
The error code in the client refers to
"Software caused connection abort.
 An established connection was aborted by the software in your host computer, possibly due to a data transmission time-out or protocol error."
(https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2)

I'm unsure what might have caused it. Did it immediately connect disconnect ?

**Comment by Zero3K** [comment]
No, I just clicked the Terminate/Disconnect button.

**Comment by maxrigout** [comment]
then that's probably why the program terminated.
If you clicked the terminate button, the server shutdown and therefore the client wasn't connected to the server anymore.
If you clicked the disconnect button the client disconnected from the server and therefore the server wasn't sending any inputs.
There is one issue though, and that is if you disconnect while the mouse is on the other screen, you still need to bring the mouse back to the server screen before being able to control the server computer.

**Comment by Zero3K** [comment]
I think that it should use words instead of showing an error code when terminating the server/disconnecting the client. Also, it should show "Connected to port 27015" instead of "Connected! 27015".
